#!/usr/bin/env bash

echo "Sourcing ~/.profile"
source "$HOME/.config/shellrc"

if [[ $SHELL == "bash" ]]; then
    source ~/.bashrc
fi

if [[ $SHELL == "zsh" ]]; then
    source ~/.zshrc
fi
. "$HOME/.rye/env"
. "/home/meowxiik/.local/share/cargo/env"
