#!/usr/bin/env bash

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

echo "Sourcing ~/.profile"
source "/home/$USER/.config/shellrc"

if hash pyenv &> /dev/null; then 
  eval "$(pyenv init --path)"
fi
